version: "3.5"
services:
  app:
    container_name: pkid
    image: jimber/pkid:staging
    restart: always
    build: .
    ports:
      - "8080:8080"
    links:
      - "redis"
    depends_on:
      - redis
    environment:
      - redishost=redis

  redis:
    container_name: pkid_redis
    image: redis
    restart: always
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - pkid-data:/data

networks:
  default:
    external:
      name: jimber_proxy_net

volumes:
  pkid-data:
    name: pkid-data
