# Default values for 3botlogin.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


environment: staging



image:
        name: pkid
        repository: threefolddev/pkid
        tag: staging

redisImage:
  name: redis-staging
  tag: latest

ingress:
  # Used to create an Ingress record.
  hosts:
    - name: pkid.staging.threefold.me
      service: pkid-staging
      path: /
      port: 80
