# Default values for 3botlogin.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


environment: staging



image:
        name: pkid
        repository: threefolddev/pkid
        tag: staging

redisImage:
  name: redis-staging
  tag: latest

ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: "PUT, GET, POST, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/cors-allow-headers: "DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization"      
  # Used to create an Ingress record.
  hosts:
    - name: pkid.staging.threefold.me
      service: pkid-staging
      path: /
      port: 80
