apiVersion: v1
kind: Service
metadata:
  labels:
    app:  {{ template "releaseName" . }}
  name: redis-{{ .Values.environment}}
spec:
  ports:
    - port: 6379
      protocol: TCP
      targetPort: 6379
  selector:
    app: redis-{{ .Values.environment}}
  type: ClusterIP
status:
  loadBalancer: {}
