name: staging

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+-rc[0-9]+"
  
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Log into Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.TFDOCKERHUB_USERNAME }}
          password: ${{ secrets.TFDOCKERHUB_PASSWORD }}
      - name: Building PKID for Staging 
        run: docker build . threefolddev/pkid:staging-${{ github.sha }}
      - name: Push the Docker image
        run: docker push threefolddev/pkid:staging-${{ github.sha }}
        
  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create kubeconfig
        run: |
          mkdir ${HOME}/.kube
          echo ${{ secrets.TF_KUBE_CONFIG }} | base64 --decode > ${HOME}/.kube/config        
      - name: Upgrade staging on cluster
        run: helm upgrade --install pkid helm_files -f helm_files/valuesStaging.yaml --set image.tag=staging-${{ github.sha }} -n threefoldconnect-staging
