name: staging

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+-rc[0-9]+"
  
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Log into GitHub Container Registry
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Building PKID for Staging 
        run: docker build . -t jimber/pkid:staging-${{ github.sha }}
      - name: Push the Docker image
        run: docker push jimber/pkid:staging-${{ github.sha }}
        
  deploy:
    needs: build
    runs-on: whale-replacement
    steps:
#       - name: Pull the Docker image
#         run: docker pull jimber/pkid:staging-${{ github.sha }}
#       - name: Killing old docker 
#         run: docker rm -f pkid || true
#       - name: Testing docker
#         run: docker-compose up -d
        - name : test
          run : ls -alh
        - name: test
          run : pwd
        - name: whoami
          run : hostname
        - name: clone
          run : git clone https://github.com/threefoldtech/pkid && cd pkid
        - name: test
          run: docker-compose up -d
          
        

